task: qna_local_docs

llm:
  org: openai
  model: gpt-3.5-turbo
  temperature: 0
  max_tokens: 3000

data:
  dir: reports
  about: "Uber 10Q Filing"

memory:
  dir: uber_10q
  max_input_size: 2500
  num_outputs: 1000
  max_chunk_overlap: 0.05
  chunk_size_limit: 1000
